Document: passenger-common
Title: Debian passenger-common Manual
Author: <insert document author here>
Abstract: This manual describes what passenger-common is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/passenger-common/passenger-common.sgml.gz

Format: postscript
Files: /usr/share/doc/passenger-common/passenger-common.ps.gz

Format: text
Files: /usr/share/doc/passenger-common/passenger-common.text.gz

Format: HTML
Index: /usr/share/doc/passenger-common/html/index.html
Files: /usr/share/doc/passenger-common/html/*.html
